namespace BC2G.Graph.Db.Neo4jDb.BitcoinStrategies;

public class T2TEdgeStrategy : BitcoinEdgeStrategy
{
    public const string labels = "Tx";

    /// Note that the ordre of the items in this array should 
    /// match those in the `GetCSV` method.
    private readonly Property[] _properties =
    [
        Props.T2TEdgeSourceTxid,
        Props.T2TEdgeTargetTxid,
        Props.EdgeType,
        Props.EdgeValue,
        Props.Height
    ];

    public override string GetCsvHeader()
    {
        return string.Join(
            Neo4jDb.csvDelimiter,
            from x in _properties select x.CsvHeader);
    }

    public override string GetCsv(IGraphComponent edge)
    {
        return GetCsv((T2TEdge)edge);
    }

    public static string GetCsv(T2TEdge edge)
    {
        return string.Join(Neo4jDb.csvDelimiter,
        [
            edge.Source.Txid,
            edge.Target.Txid,
            edge.Type.ToString(),
            edge.Value.ToString(),
            edge.BlockHeight.ToString()
        ]);
    }

    public override string GetQuery(string csvFilename)
    {
        // The following is an example of the query generated by this method.
        // Indentation and line break is added for readability and is not 
        // included in the generated query.
        //
        //
        // LOAD CSV WITH HEADERS FROM 'file:///filename.csv' AS line
        // FIELDTERMINATOR '	'
        //
        // MATCH
        //     (source:Tx {Txid:line.SourceId}),
        //     (target:Tx {Txid:line.TargetId}),
        //     (block:Block {Height:toInteger(line.Height)})
        //
        // CREATE (source)-[:Redeems {Height:toInteger(line.Height), Value:toFloat(line.Value)}]->(block)
        // CREATE (block)-[:Creates  {Height:toInteger(line.Height), Value:toFloat(line.Value)}]->(target)
        //
        // WITH line, source, target, block
        //
        // CALL apoc.create.relationship(
        //     source,
        //     line.EdgeType,
        //     {
        //         Height:toInteger(line.Height),
        //         Value:toFloat(line.Value)
        //     },
        //     target)
        // YIELD rel
        // RETURN distinct 'DONE'
        //

        string l = Property.lineVarName, s = "source", t = "target", b = "block";

        var builder = new StringBuilder(
            $"LOAD CSV WITH HEADERS FROM '{csvFilename}' AS {l} " +
            $"FIELDTERMINATOR '{Neo4jDb.csvDelimiter}' ");

        builder.Append(
            $"MATCH " +
            $"({s}:{TxNodeStrategy.labels} {{{Props.T2TEdgeSourceTxid.GetSetter()}}}), " +
            $"({t}:{TxNodeStrategy.labels} {{{Props.T2TEdgeTargetTxid.GetSetter()}}}), " +
            $"({b}:{BlockGraphStrategy.labels} {{{Props.Height.GetSetter()}}}) ");

        builder.Append(
            GetRedeemsEdgeQuery(b, s) + " " +
            GetCreatesEdgeQuery(b, t) + " ");

        builder.Append(
            $"WITH {l}, {s}, {t}, {b} ");

        builder.Append(
            GetApocCreateEdgeQuery(GetEdgePropertiesBase(), s, t));

        builder.Append(
            $" RETURN distinct 'DONE'");

        return builder.ToString();
    }
}
