// <auto-generated />
using BC2G.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BC2G.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220823130929_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BC2G.Model.Utxo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedIn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CreatedInCount")
                        .HasColumnType("integer");

                    b.Property<string>("ReferencedIn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReferencedInCount")
                        .HasColumnType("integer");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Utxo");
                });
#pragma warning restore 612, 618
        }
    }
}
